### ISSUE TITLE
程序唤醒错误，设置唤醒mac系统APP结果唤醒的是window的应用

### ISSUE THREAD

**Issue by PythonSONGs** [gbammc/Thor#10]
首先谢谢大神开发这么实用的APP，使用Thor切换app确实很方便很好用。谢谢！
不过我最近在使用过程中发现有个问题无法解决：
就是我的系统同时有mac版chrome，通过parallels安装win8.1系统里面也有一个window版本的chrome。之前使用的过程中一直可以正常唤醒mac系统里面的chrome但是今天不知为何唤醒的是parallels里面win8.1的chrome。
mac版chrom路径：/Applications/Google\ Chrome.app
win8.1版chrome路径：/Users/koukomatsu/Applications\ \(Parallels\)/\{61920071-df00-4a6c-9235-7720a9f878e3\}\ Applications.localized/Google\ Chrome.app
请问这个我自己是否有办法处理？如果有请问如何处理？

**Comment by maxiloEmmmm** [comment]
啊啊啊啊啊啊啊 我也是这样 我现在只能卸载 Parallels Desktop 中的chrome

**Comment by codeshif** [comment]
可能与你选择设置快捷键时的APP有关系吧，不然你可以修改一下虚拟机里面Chrome的名字。

**Comment by gbammc** [comment]
现在还能复现吗？

**Comment by PythonSONGs** [comment]
不好意思，换电脑了，现在没有使用了。

**Comment by gbammc** [comment]
好的
