### ISSUE TITLE
[Feature request] Temporarily disable shortcuts

### ISSUE THREAD

**Issue by kenji21** [gbammc/Thor#18]
With Thor, I finally made Function 1-12 keys useful, thanks for this piece of software

Will you be opened to a PR to add a feature in the menubar drop down (like preferences) to be able to disable / enable Thor shortcuts

My use-case is that to configure htop, function keys are needed (but my mapping makes me changing app...)

Today I quit the app, and then relaunch it

**Comment by gbammc** [comment]
PR is welcome~

**Comment by kenji21** [comment]
I'm near ready to PR  from https://github.com/kenji21/Thor, but I miss two translations before:

```
"Disable Shortcuts" = "?";

"Enable Shortcuts" = "?";
```

**Comment by gbammc** [comment]
I suggest:
```
"Disable Shortcuts" = "停用快捷键";

"Enable Shortcuts" = "启用快捷键";
```

**Comment by kenji21** [comment]
❤️

**Comment by kenji21** [comment]
should I close this issue or you close it after a new version of the app containing this feature is published ?

**Comment by gbammc** [comment]
I will close this issue after it is published :)

**Comment by gbammc** [comment]
It's released in v1.5.2.

**Comment by kenji21** [comment]
I don't see any 1.5.2 tags, and checking for updates shows 1.5.0 is the last one (as GitHub does):

`Thor 1.5.0 is currently the newest version available.`

**Comment by kenji21** [comment]
👌
<img width="401" alt="Screenshot 1" src="https://user-images.githubusercontent.com/1105089/86883359-21ce2c80-c0f2-11ea-80cc-e9b2e981bcd8.png">
