### ISSUE TITLE
Shortcuts for Chrome apps disappear upon logout/reboot

### ISSUE THREAD

**Issue by finferflu** [gbammc/Thor#20]
Hi, 

With Google Chrome, if you go to **Settings** > **More Tools** > **Create shortcut**, you can create a Chrome window that acts as its own app. I use this extensively, and it's great in combination with Thor. However, every time I log out or reboot, the shortcuts for these "apps" simply disappear. Please advise.

Thanks!

**Comment by gbammc** [comment]
That's because the MAS version is constrained by the App Sandbox. Thor is not allow to access the folder where the Chrome Apps located after you log out or reboot. I recommend  you to use the version in the release pages:
https://github.com/gbammc/Thor/releases

Hope it helps and thanks for using Thor :)

**Comment by finferflu** [comment]
Thanks for letting me know, @gbammc, I'll try that and will reopen this issue if I run into any problems. Thanks!

**Comment by 5macro** [comment]
> That's because the MAS version is constrained by the App Sandbox. Thor is not allow to access the folder where the Chrome Apps located after you log out or reboot. I recommend you to use the version in the release pages:
> https://github.com/gbammc/Thor/releases
> 
> Hope it helps and thanks for using Thor :)

@gbammc Could the issue only be addressed by downloading and installing from the release page manually? I tried to install through brew also not work 😢

**Comment by TheoMcGinley** [comment]
For everyone having this issue - moving the app to /Applications fixes the issue for me, the shortcuts no longer disappear.
