### ISSUE TITLE
[feature request] Set folder to a hotkey

### ISSUE THREAD

**Issue by dustatron** [gbammc/Thor#21]
I wonder if you could enable setting a folder to a hotkey. 

I would like to be able to bind a project folder to a key so that I can have finder auto open at a specific directory.

**Comment by codeshif** [comment]
You can use it open the terminal then use `open ./` open the path of your finder.

**Comment by gbammc** [comment]
Technically every file can set a hotkey, but I don't want to make Thor so complicated for now. @codeshif 's advice can be the solution.
