### ISSUE TITLE
重启后,已添加的应用消失了

### ISSUE THREAD

**Issue by lihuacai168** [gbammc/Thor#22]
# 前置条件
- 应用不在应用列表中

# 复现步骤
- 添加应用程序,搜索应用,例如Toolbox安装的Pycharm,或者brew安装的iterm2
- 设置快捷键 
- 重启电脑

# 实际结果
- 快捷键中的Pycharm,iterm2消失了

**Comment by gbammc** [comment]
感谢反馈，新版已经修复这个问题了，可以在 MAS 更新一下。
