### ISSUE TITLE
Unable to add Application made with 'appify' script

### ISSUE THREAD

**Issue by thebitstick** [gbammc/Thor#23]
[This script](https://gist.github.com/mathiasbynens/674099) allows me to create a simple Application out of a shell script or other executable.

For some reason, I am unable to add one of these applications through Thor.
If I knew how, I'd provide debugging, but there isn't any option to do so.

**Comment by thebitstick** [comment]
Somehow removing a custom icon and setting a proper icon via Info.plist fixes this?

**Comment by gbammc** [comment]
> Somehow removing a custom icon and setting a proper icon via Info.plist fixes this?

So is it solved?

**Comment by thebitstick** [comment]
For me, yes, but I'm just wondering what could have caused Thor to ignore applications without a proper Info.plist. Could cause problems for others.

**Comment by gbammc** [comment]
Thor needs the correct icon file name to find the image that will display in the list.

**Comment by thebitstick** [comment]
Ah okay. I think as long as you've found the problem in this issue, if anyone else has issues they can just find this. It's good to close now.
