### ISSUE TITLE
Thor is damaged and can't be opened

### ISSUE THREAD

**Issue by mastercyb** [gbammc/Thor#30]
Installation using brew and direct binary download. Installation using appstore works perfectly

<img width="306" alt="Screenshot 2020-11-18 at 13 51 05" src="https://user-images.githubusercontent.com/410789/99490876-aafd4600-29a5-11eb-9979-77ca0a2e1d1c.png">

<img width="315" alt="Screenshot 2020-11-18 at 13 55 22" src="https://user-images.githubusercontent.com/410789/99490905-b94b6200-29a5-11eb-8183-742a80a4dc3e.png">

**Comment by gbammc** [comment]
Please check this one #6

**Comment by gbammc** [comment]
From v1.5.5, Thor is notarized, please check this out. Thanks for using Thor!
