### ISSUE TITLE
Start at login not work

### ISSUE THREAD

**Issue by monlite** [gbammc/Thor#31]
I checked start at login, but it doesn't work after restart.

Thor Version: 1.5.3
OS Version: Mojave 10.14.6 (18G6042)

**Comment by gbammc** [comment]
@monlite MAS or Github version?

**Comment by monlite** [comment]
@gbammc I tried both latest version 1.5.5 from GitHub and MAS, and it didn't work. But I manually add Thor to the "System Preferences" > "Users & Groups" > "Login Items", it works normally.
![image](https://user-images.githubusercontent.com/20237633/102031234-50aea400-3df0-11eb-8941-db9d9b6326ad.png)
