### ISSUE TITLE
Unable to add Calendar.app to app list

### ISSUE THREAD

**Issue by chefino** [gbammc/Thor#33]
Hi,

Macbook Air M1
OS X Big Sur 11.0.1 (20B29)
Thor version: latest from Mac App Store (2020-12-09)

When I try to add Calendar.app by browsing to it and clicking Open, nothing happens, the app is not added to the list. Even tried to create an alias to it and add that, also not working.

Other apps seem to be adding to the list as expected.
Can you please help?

Also, if an app is on another virtual screen or full-screen mode, invoking the app designated shortcut doesn't take me to the app, only the app taskbar changes (top row on the screen, e.g. Mail.app).

<img width="472" alt="image" src="https://user-images.githubusercontent.com/4114876/101610648-d3a6b780-3a08-11eb-97f5-7fe91f176bef.png">

**Comment by gbammc** [comment]
fixed in v1.5.5
