### ISSUE TITLE
在Big Sur 11.3.1上无法添加homebrew安装的app到list中

### ISSUE THREAD

**Issue by 5macro** [gbammc/Thor#40]
包括homebrew安装的所有app和从App Store中安装的部分app（lemon cleaner lite）均无法添加到list中，即选中后list依然是空白，但是部分的Mac自带应用可以添加到list中（Safari等）

**Comment by 5macro** [comment]
在另外一台mac上复现了，表现都是app刚安装后无法添加到Thor的list中，但是过了一段时间后就可以添加了。

**Comment by gbammc** [comment]
AppStore 安装的我无法重现问题，homebrew 安装的 app 是在哪个目录？

**Comment by 5macro** [comment]
> AppStore 安装的我无法重现问题，homebrew 安装的 app 是在哪个目录？

`/Applications`。
我发现刚刚安装的app都不行，但是过一个一段时间就可以了。

**Comment by gbammc** [comment]
能帮忙调试下是什么原因么？我的 Mac 也是 11.3.1，但是没重现

**Comment by 5macro** [comment]
> 能帮忙调试下是什么原因么？我的 Mac 也是 11.3.1，但是没重现

好，如果我再遇到的话，我把日志放出来，但是目前这个貌似不再出现了，也有可能是我一开始遇到的时候是刚刚重装系统，难道是Mac的file system的indexing会影响Thor的检索？Anyway，我就先close掉这个issue了
