### ISSUE TITLE
设置快捷键的问题。

### ISSUE THREAD

**Issue by lizonggang** [gbammc/Thor#42]
我设置不了Command + 数字  例如 command 1
当设置了command 1 只会显示command V
![1632021426605](https://user-images.githubusercontent.com/4124582/133914271-c7159cd9-521f-42c1-a1b2-1b19ebac7a82.jpg)
我不知道应该怎么办。

**Comment by gbammc** [comment]
我这边一直都是可以的，你方便调试下是什么原因吗？

**Comment by lizonggang** [comment]
抱歉我来晚了， 应该是和其它的软件快捷键有冲突。
