### ISSUE TITLE
Thor for Windows?

### ISSUE THREAD

**Issue by JohnDohe** [gbammc/Thor#43]
Hi,

Love Thor for my Mac!

I would LOVE to have Thor for my Windows pc's too!!!

Do you intend to make Thor work in Windows too?

Thanks!

**Comment by gbammc** [comment]
Thanks for your love to Thor, but I don't have a PC, so it would't have a Windows version.

**Comment by JohnDohe** [comment]
get one?

*****************************************************************************************************************

**Comment by gbammc** [comment]
Haha
