### ISSUE TITLE
Thor shortcut

### ISSUE THREAD

**Issue by jvansant** [gbammc/Thor#47]
The "Enable shortcut" toggle in the Thor settings seems to do nothing. I would prefer to use shift control opt cmd + T for a different application. Currently no matter how I configure the Thor settings this shortcut is not able to be assigned to another application.

**Comment by kenji21** [comment]
I think you misunderstood what the shortcut does:

<img width="288" alt="Screenshot 3" src="https://user-images.githubusercontent.com/1105089/149881878-ecfc8735-3a25-48eb-a047-c8663d436193.png">

**Comment by fuzzyweapon** [comment]
Although they misunderstood the `Enable shortcut` option, this was confusing to me too and should probably be clarified, such as, `Enable Custom Shortcuts`


However, I think their issue is still value.  I understand what they are saying.  Thor will hog up that key binding slot (for hiding and showing the tray icon) globally and there is no way to free it up.  What they want is the freedom to not have Thor take up that binding.

I can relate to this as an IDE user.  This is very problematic and there is no shortcut to be able to easily turn Thor shortcuts on and off (a toggle, not something that re-enables itself so quickly; though this feature is cool, it doesn't allow me ever enough time to do what I need, even at 1s).

Besides, using this shortcut only enables me to have to use my mouse to interact with Thor which feels weird.  It doesn't feel very high value compared to have this binding forcefully eaten up by Thor when I can use an existing shortcut to minimize it and use my mouse then to restore it from the dock that way anyways.

**Comment by wiiwaker** [comment]
I second this issue and hope it will be implemented soon.
