### ISSUE TITLE
[Feature request] show/hide app

### ISSUE THREAD

**Issue by txchen** [gbammc/Thor#5]
Just like iTerm global shortcut key, when the app is foreground and active, press the shortcut will hide that app. So you can toggle the app, instead of just bring it foreground.

I think this is useful because if you launch the wrong app, press it again to hide it. Hope you can support that :)

**Comment by txchen** [comment]
Thanks for the super swift commit! Just awesome!

**Comment by gbammc** [comment]
@txchen Wish you will enjoy it!
