### ISSUE TITLE
How to export/import Thor settings?

### ISSUE THREAD

**Issue by wenfangdu** [gbammc/Thor#54]
I didn't find the export/import function on the settings page, but [this comment](https://github.com/gbammc/Thor/issues/15#issuecomment-624088881) says it's already supported.

![image](https://user-images.githubusercontent.com/28700378/201509978-0aa44c3d-268e-44d2-a6e7-90b1dac23b29.png)

**Comment by gbammc** [comment]
Click the icon in the status bar, and they just above the "Quit" button
<img width="140" alt="Screenshot 2022-11-13 at 22 27 56" src="https://user-images.githubusercontent.com/1791294/201527018-662f6625-9a8a-44f2-829d-c36cbfc2b57b.png">

**Comment by wenfangdu** [comment]
@gbammc Ah, right, I hid Thor in the menu bar.
