### ISSUE TITLE
How to remove Thor from "Allow in the Background"

### ISSUE THREAD

**Issue by wenfangdu** [gbammc/Thor#59]
Since I've used [Karabiner to replace Thor](https://apple.stackexchange.com/a/462042/424683), I wanted to remove all Thor-related files, I followed [this guide](https://droidwin.com/remove-deleted-apps-from-background-login-items-in-ventura/), but it stays in the "Allow in the Background" tab, how to remove it?
![image](https://github.com/gbammc/Thor/assets/28700378/ac05e8dc-2af1-4c63-a69a-f3acc6850d0d)
I also tried system-level grepping for "Thor", but with no result.

**Comment by gbammc** [comment]
![image](https://github.com/gbammc/Thor/assets/1791294/ecc5af6a-ba2c-4be2-9b3a-0e708b9123a4)
Try to remove the helper at this path.
