### ISSUE TITLE
"Thor.app" is damaged

### ISSUE THREAD

**Issue by ilearnio** [gbammc/Thor#6]
I just downloaded the latest release app "Thor_1.2.0.zip" and got this when tried to open it

![image](https://user-images.githubusercontent.com/14331216/39039386-1addeb3c-448e-11e8-9de6-2a10f2c8f176.png)

I'm on High Sierra, Macbook Pro

**Comment by gbammc** [comment]
It's caused by the 'Gatekeeper'. You can solve it by follow this [page](https://www.santoshsrinivas.com/disable-gatekeeper-in-macos-sierra/), or you can install Thor in [Mac App Store](https://itunes.apple.com/app/thor/id1120999687?ls=1&mt=12)

And can you tell me where you find this repo?

Thanks for using Thor!

**Comment by ilearnio** [comment]
It works! Fantastic! Was looking for such app for so long.

I found this repo here https://github.com/serhii-londar/open-source-mac-os-apps

Thanks a ton!

**Comment by kenji21** [comment]
> It's caused by the 'Gatekeeper'. You can solve it by follow this [page](https://www.santoshsrinivas.com/disable-gatekeeper-in-macos-sierra/), or you can install Thor in [Mac App Store](https://itunes.apple.com/app/thor/id1120999687?ls=1&mt=12)
> 
> And can you tell me where you find this repo?
> 
> Thanks for using Thor!

Got it when upgrading to 1.5.3, and to fix this I do : `xattr -dr com.apple.quarantine /Applications/Thor.app/`

Maybe zip shipping is not the best way, can shipping through a dmg prevent this ?

**Comment by gbammc** [comment]
> > It's caused by the 'Gatekeeper'. You can solve it by follow this [page](https://www.santoshsrinivas.com/disable-gatekeeper-in-macos-sierra/), or you can install Thor in [Mac App Store](https://itunes.apple.com/app/thor/id1120999687?ls=1&mt=12)
> > And can you tell me where you find this repo?
> > Thanks for using Thor!
> 
> Got it when upgrading to 1.5.3, and to fix this I do : `xattr -dr com.apple.quarantine /Applications/Thor.app/`
> 
> Maybe zip shipping is not the best way, can shipping through a dmg prevent this ?

Why dmg can prevent this? Is there any info?

**Comment by gbammc** [comment]
> > It's caused by the 'Gatekeeper'. You can solve it by follow this [page](https://www.santoshsrinivas.com/disable-gatekeeper-in-macos-sierra/), or you can install Thor in [Mac App Store](https://itunes.apple.com/app/thor/id1120999687?ls=1&mt=12)
> > And can you tell me where you find this repo?
> > Thanks for using Thor!
> 
> Got it when upgrading to 1.5.3, and to fix this I do : `xattr -dr com.apple.quarantine /Applications/Thor.app/`
> 
> Maybe zip shipping is not the best way, can shipping through a dmg prevent this ?

I'm curious, why not download form MAS?

**Comment by kenji21** [comment]
Because I was using my home compiled version before you merge my contribution :D

**Comment by gbammc** [comment]
From v1.5.5, Thor is notarized, it would not show this alert any more.
