### ISSUE TITLE
Repeat shortcut to cycle app windows

### ISSUE THREAD

**Issue by jelder** [gbammc/Thor#7]
First of all, thank you! Thor is _exactly_ what I needed. I had tried to build this functionality using Automator Services but they are way too slow for interactive use.

I use Thor to switch between iTerm 2, VS Code, and Chrome, and I frequently have multiple windows open for each. I wish that instead of hitting command-backtick to cycle those app windows, I could repeatedly hit the shortcut assigned in Thor.

**Comment by kenji21** [comment]
same forkflow here, but I make the windows to hide when hitting shortcut again (so I "call" iTerm, and then make it hide to go back to previous app)

edit : 
````
cmd + `
````
might do what you want

**Comment by gbammc** [comment]
> same forkflow here, but I make the windows to hide when hitting shortcut again (so I "call" iTerm, and then make it hide to go back to previous app)
> 
> edit :
> 
> ```
> cmd + `
> ```
> 
> might do what you want

That's right.
