### ISSUE TITLE
macos更新sequoia之后，option+字母的快捷方式不生效了

### ISSUE THREAD

**Issue by louis-ly** [gbammc/Thor#74]
macos更新sequoia之后，option+字母的快捷方式不生效了，你们有遇到吗
ctrl+字母是ok的，但是我已经用了一两年option了，要改有点不习惯唉，怎么办

**Comment by Enoooch** [comment]
Same here, the option key does not work on Sequoia macOS.

**Comment by Enoooch** [comment]
@louis-ly Hi,
Update to version 1.5.14 and reset the shortcut keys.
Everything works as usual.

**Comment by louis-ly** [comment]
> @louis-ly Hi, Update to version 1.5.14 and reset the shortcut keys. Everything works as usual.

Wow 🤩, this is incredibly great news! This issue has been troubling me for so long. Thank you so much for bringing me this fantastic news. Big thumbs up ღ( ´･ᴗ･` )
